// src/utils/mockData.js

/**
 * Test üçün istifadə edilən əməkdaşların verilənlərini qaytarır
 * @returns {Array} - Test əməkdaşları siyahısı
 */
export const getMockEmployees = () => {
  return [
    {
      id: "1",
      empNo: "HLD01",
      name: "Şirin Camalli Rasad Oglu",
      firstName: "Şirin",
      lastName: "Camalli",
      email: "sirin.camalli@almetholding.com",
      phone: "+994 50 123 45 67",
      dateOfBirth: "1975-04-15",
      address: "Baku, Narimanov district, Tabriz str. 15",
      emergencyContact: "Leyla Camalli: Wife: +994 50 987 65 43",
      businessFunction: "Holding",
      department: "BUSINESS DEVELOPMENT",
      unit: "STRATEGY EXECUTION",
      jobFunction: "DEPUTY CHAIRMAN ON FINANCE & BUSINESS DEVELOPMENT",
      jobTitle: "Direktor müavini",
      positionGroup: "VC",
      grade: "8",
      lineManager: null,
      lineManagerHcNumber: null,
      startDate: "2015-01-15",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "Executive leadership with extensive experience in finance and business development.",
      profileImage: null,
      expertise: ["Strategic Planning", "Finance Management", "Business Development", "Leadership"]
    },
    {
      id: "2",
      empNo: "HLD03",
      name: "Safa Nacafova Mammadli Qizi",
      firstName: "Safa",
      lastName: "Nacafova",
      email: "safa.nacafova@almetholding.com",
      phone: "+994 50 234 56 78",
      dateOfBirth: "1992-05-15",
      address: "Baku, Yasamal district, Azadliq ave. 25",
      emergencyContact: "Elvin Nacafov: Father: +994 50 876 54 32",
      businessFunction: "Holding",
      department: "ADMINISTRATIVE",
      unit: "ADMINISTRATION",
      jobFunction: "ADMINISTRATION SPECIALIST",
      jobTitle: "Ofis-menecer",
      positionGroup: "JUNIOR SPECIALIST",
      grade: "2",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2023-06-15",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "Responsible for office management and administrative support.",
      profileImage: null,
      expertise: ["Office Management", "Administrative Support", "Communication"]
    },
    {
      id: "3",
      empNo: "HLD06",
      name: "Sebuhi Isayev Samir Oglu",
      firstName: "Sebuhi",
      lastName: "Isayev",
      email: "sebuhi.isayev@almetholding.com",
      phone: "+994 50 345 67 89",
      dateOfBirth: "1988-11-22",
      address: "Baku, Khatai district, Ahmad Rajabli str. 10",
      emergencyContact: "Samir Isayev: Father: +994 50 765 43 21",
      businessFunction: "Holding",
      department: "COMPLIANCE",
      unit: "BUSINESS SUPPORT",
      jobFunction: "LEGAL",
      jobTitle: "Hüquqşünas - komplayns üzre menecer",
      positionGroup: "HEAD OF DEPARTMENT",
      grade: "6",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2022-09-01",
      endDate: null,
      status: "ON LEAVE",
      tags: ["Sick Leave"],
      office: "Baku HQ",
      notes: "Legal expert specializing in compliance and regulatory matters.",
      profileImage: null,
      expertise: ["Legal Compliance", "Corporate Law", "Risk Management", "Contract Review"]
    },
    {
      id: "4",
      empNo: "HLD10",
      name: "Emin Eminzade Mubarak Oglu",
      firstName: "Emin",
      lastName: "Eminzade",
      email: "emin.eminzade@almetholding.com",
      phone: "+994 50 456 78 90",
      dateOfBirth: "1990-03-10",
      address: "Baku, Sabunchu district, Salyan highway 45",
      emergencyContact: "Mubarak Eminzade: Father: +994 50 654 32 10",
      businessFunction: "Holding",
      department: "FINANCE",
      unit: "FINANCE OPERATIONS",
      jobFunction: "SENIOR BUDGETING & CONTROLLING SPECIALIST",
      jobTitle: "Mühasib",
      positionGroup: "SENIOR SPECIALIST",
      grade: "4",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2023-02-15",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "Senior finance professional with expertise in budgeting and financial controlling.",
      profileImage: null,
      expertise: ["Financial Analysis", "Budgeting", "Cost Control", "Accounting"]
    },
    {
      id: "5",
      empNo: "HLD05",
      name: "Aysel Mahmudova Farid Qizi",
      firstName: "Aysel",
      lastName: "Mahmudova",
      email: "aysel.mahmudova@almetholding.com",
      phone: "+994 50 567 89 01",
      dateOfBirth: "1995-08-20",
      address: "Baku, Nizami district, Nizami str. 30",
      emergencyContact: "Farid Mahmudov: Father: +994 50 543 21 09",
      businessFunction: "Holding",
      department: "HR",
      unit: "BUSINESS SUPPORT",
      jobFunction: "HR BUSINESS PARTNER",
      jobTitle: "İnsan resursları üzrə təcrübəçi",
      positionGroup: "SPECIALIST",
      grade: "3",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2024-01-10",
      endDate: null,
      status: "ON BOARDING",
      tags: [],
      office: "Baku HQ",
      notes: "New HR team member focusing on employee relations and development.",
      profileImage: null,
      expertise: ["Human Resources", "Employee Relations", "Recruitment", "Training"]
    },
    {
      id: "6",
      empNo: "GEO01",
      name: "Irakli Sabadze",
      firstName: "Irakli",
      lastName: "Sabadze",
      email: "irakli.sabadze@almetholding.com",
      phone: "+995 555 123 456",
      dateOfBirth: "1985-07-18",
      address: "Tbilisi, Vake district, Chavchavadze ave. 12",
      emergencyContact: "Ana Sabadze: Wife: +995 555 654 321",
      businessFunction: "Georgia",
      department: "OPERATIONS",
      unit: "COMMERCE",
      jobFunction: "OPERATIONS SPECIALIST",
      jobTitle: "Operations Manager",
      positionGroup: "MANAGER",
      grade: "5",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2021-05-20",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Tbilisi Office",
      notes: "Operations manager overseeing Georgia business activities.",
      profileImage: null,
      expertise: ["Operations Management", "Team Leadership", "Process Optimization", "Supply Chain"]
    },
    {
      id: "7",
      empNo: "GEO08",
      name: "Giorgi Jishkariani",
      firstName: "Giorgi",
      lastName: "Jishkariani",
      email: "giorgi.jishkariani@almetholding.com",
      phone: "+995 555 234 567",
      dateOfBirth: "1991-12-05",
      address: "Tbilisi, Saburtalo district, University str. 8",
      emergencyContact: "Nino Jishkariani: Sister: +995 555 765 432",
      businessFunction: "Georgia",
      department: "STOCK SALES",
      unit: "COMMERCE",
      jobFunction: "SALES EXECUTIVE",
      jobTitle: "Sales Representative",
      positionGroup: "SPECIALIST",
      grade: "3",
      lineManager: "Irakli Sabadze",
      lineManagerHcNumber: "GEO01",
      startDate: "2022-03-10",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Tbilisi Office",
      notes: "Sales specialist focused on Georgian market development.",
      profileImage: null,
      expertise: ["Sales", "Customer Relations", "Market Analysis", "Negotiation"]
    },
    {
      id: "8",
      empNo: "UK01",
      name: "Serena Marshall",
      firstName: "Serena",
      lastName: "Marshall",
      email: "serena.marshall@almetholding.com",
      phone: "+44 20 7123 4567",
      dateOfBirth: "1983-04-12",
      address: "London, Canary Wharf, Bank Street 25",
      emergencyContact: "James Marshall: Husband: +44 20 7987 6543",
      businessFunction: "UK",
      department: "FINANCE",
      unit: "FINANCE OPERATIONS",
      jobFunction: "DEPUTY CHAIRMAN ON COMMERCIAL ACTIVITIES EUROPE REGION",
      jobTitle: "Direktor",
      positionGroup: "DIRECTOR",
      grade: "7",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2023-01-05",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "London Office",
      notes: "Senior executive overseeing European commercial operations.",
      profileImage: null,
      expertise: ["Executive Leadership", "Commercial Strategy", "International Business", "Finance"]
    },
    {
      id: "9",
      empNo: "UK02",
      name: "Joseph Jesudas Babuji",
      firstName: "Joseph",
      lastName: "Jesudas Babuji",
      email: "joseph.jesudas@almetholding.com",
      phone: "+44 20 7234 5678",
      dateOfBirth: "1987-09-28",
      address: "London, South Kensington, Exhibition Road 15",
      emergencyContact: "Maria Babuji: Wife: +44 20 7876 5432",
      businessFunction: "UK",
      department: "FINANCE",
      unit: "FINANCE OPERATIONS",
      jobFunction: "CHIEF ACCOUNTANT",
      jobTitle: "Chief Accountant",
      positionGroup: "SENIOR SPECIALIST",
      grade: "5",
      lineManager: "Serena Marshall",
      lineManagerHcNumber: "UK01",
      startDate: "2023-04-20",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "London Office",
      notes: "Chief accountant responsible for UK financial operations.",
      profileImage: null,
      expertise: ["Accounting", "Financial Reporting", "Tax Compliance", "Audit"]
    },
    {
      id: "10",
      empNo: "TRD01",
      name: "Elvin Aliyev Rashad Oglu",
      firstName: "Elvin",
      lastName: "Aliyev",
      email: "elvin.aliyev@almetholding.com",
      phone: "+994 50 678 90 12",
      dateOfBirth: "1986-06-25",
      address: "Baku, Binagadi district, Azadliq str. 55",
      emergencyContact: "Rashad Aliyev: Father: +994 50 432 10 98",
      businessFunction: "Trading",
      department: "TRADE",
      unit: "LOGISTICS",
      jobFunction: "LOGISTICS",
      jobTitle: "Anbar üzrə təcrübəçi",
      positionGroup: "SPECIALIST",
      grade: "3",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2022-11-15",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "Logistics specialist managing warehouse operations.",
      profileImage: null,
      expertise: ["Logistics", "Warehouse Management", "Inventory Control", "Supply Chain"]
    },
    {
      id: "11",
      empNo: "TRD02",
      name: "Fuad Hasanov Ilham Oglu",
      firstName: "Fuad",
      lastName: "Hasanov",
      email: "fuad.hasanov@almetholding.com",
      phone: "+994 50 789 01 23",
      dateOfBirth: "1993-02-14",
      address: "Baku, Surakhani district, Baku-Sumgait highway 12",
      emergencyContact: "Ilham Hasanov: Father: +994 50 321 09 87",
      businessFunction: "Trading",
      department: "OPERATIONS",
      unit: "WAREHOUSE INVENTORY",
      jobFunction: "WAREHOUSE FOREMAN",
      jobTitle: "Fəhlə",
      positionGroup: "BLUE COLLAR",
      grade: "1",
      lineManager: "Elvin Aliyev Rashad Oglu",
      lineManagerHcNumber: "TRD01",
      startDate: "2024-03-01",
      endDate: null,
      status: "PROBATION",
      tags: [],
      office: "Warehouse - Surakhani",
      notes: "Warehouse worker currently under probation period.",
      profileImage: null,
      expertise: ["Warehouse Operations", "Material Handling", "Safety Procedures"]
    },
    {
      id: "12",
      empNo: "DUB01",
      name: "Ahmed Al-Rashid",
      firstName: "Ahmed",
      lastName: "Al-Rashid",
      email: "ahmed.alrashid@almetholding.com",
      phone: "+971 50 123 4567",
      dateOfBirth: "1984-11-30",
      address: "Dubai, Business Bay, Bay Square 10",
      emergencyContact: "Fatima Al-Rashid: Wife: +971 50 987 6543",
      businessFunction: "Trading",
      department: "BUSINESS DEVELOPMENT",
      unit: "BUSINESS DEVELOPMENT",
      jobFunction: "BUSINESS DEVELOPMENT DIRECTOR",
      jobTitle: "Satış üzrə mütəxəssis",
      positionGroup: "DIRECTOR",
      grade: "7",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2020-08-15",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Dubai Office",
      notes: "Business development director for Middle East operations.",
      profileImage: null,
      expertise: ["Business Development", "Sales Strategy", "Market Expansion", "Partnership Development"]
    },
    {
      id: "13",
      empNo: "HLD06",
      name: "Nigar Hasanova Tofiq Qizi",
      firstName: "Nigar",
      lastName: "Hasanova",
      email: "nigar.hasanova@almetholding.com",
      phone: "+994 50 890 12 34",
      dateOfBirth: "1994-01-18",
      address: "Baku, Nasimi district, Fuzuli str. 20",
      emergencyContact: "Tofiq Hasanov: Father: +994 50 210 98 76",
      businessFunction: "Holding",
      department: "HR",
      unit: "BUSINESS SUPPORT", 
      jobFunction: "HR BUSINESS PARTNER",
      jobTitle: "İnsan resursları üzrə mütəxəssis",
      positionGroup: "SPECIALIST",
      grade: "3",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2023-09-20",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "HR specialist focusing on employee development and performance management.",
      profileImage: null,
      expertise: ["Human Resources", "Performance Management", "Employee Development", "Training"]
    },
    {
      id: "14",
      empNo: "TRD03",
      name: "Orkhan Mammadov Farid Oglu",
      firstName: "Orkhan",
      lastName: "Mammadov",
      email: "orkhan.mammadov@almetholding.com",
      phone: "+994 50 901 23 45",
      dateOfBirth: "1989-07-08",
      address: "Baku, Garadagh district, Lokbatan settlement 5",
      emergencyContact: "Farid Mammadov: Father: +994 50 109 87 65",
      businessFunction: "Trading",
      department: "OPERATIONS",
      unit: "LOGISTICS",
      jobFunction: "OPERATIONS MANAGER",
      jobTitle: "Əməliyyatlar meneceri",
      positionGroup: "MANAGER",
      grade: "5",
      lineManager: "Ahmed Al-Rashid",
      lineManagerHcNumber: "DUB01",
      startDate: "2021-12-01",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "Operations manager overseeing logistics and supply chain activities.",
      profileImage: null,
      expertise: ["Operations Management", "Logistics", "Supply Chain", "Process Improvement"]
    },
    {
      id: "15",
      empNo: "UK03",
      name: "Emma Thompson",
      firstName: "Emma",
      lastName: "Thompson",
      email: "emma.thompson@almetholding.com",
      phone: "+44 20 7345 6789",
      dateOfBirth: "1990-05-14",
      address: "London, Greenwich, Royal Naval College 8",
      emergencyContact: "David Thompson: Husband: +44 20 7765 4321",
      businessFunction: "UK",
      department: "ADMINISTRATIVE",
      unit: "ADMINISTRATION",
      jobFunction: "ADMINISTRATION SPECIALIST",
      jobTitle: "Administrative Assistant",
      positionGroup: "JUNIOR SPECIALIST",
      grade: "2",
      lineManager: "Serena Marshall",
      lineManagerHcNumber: "UK01",
      startDate: "2024-02-01",
      endDate: null,
      status: "ON BOARDING",
      tags: [],
      office: "London Office",
      notes: "New administrative assistant currently in onboarding process.",
      profileImage: null,
      expertise: ["Administrative Support", "Office Management", "Communication", "Documentation"]
    },
    {
      id: "16",
      empNo: "GEO03",
      name: "Nino Kvaratskhelia",
      firstName: "Nino",
      lastName: "Kvaratskhelia",
      email: "nino.kvaratskhelia@almetholding.com",
      phone: "+995 555 345 678",
      dateOfBirth: "1987-09-03",
      address: "Tbilisi, Old Town, Betlemi str. 5",
      emergencyContact: "Giorgi Kvaratskhelia: Brother: +995 555 876 543",
      businessFunction: "Georgia",
      department: "FINANCE",
      unit: "FINANCE OPERATIONS",
      jobFunction: "CHIEF ACCOUNTANT",
      jobTitle: "Baş mühasib",
      positionGroup: "SENIOR SPECIALIST",
      grade: "5",
      lineManager: "Irakli Sabadze",
      lineManagerHcNumber: "GEO01",
      startDate: "2020-04-15",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Tbilisi Office",
      notes: "Chief accountant responsible for Georgia financial operations and compliance.",
      profileImage: null,
      expertise: ["Accounting", "Financial Reporting", "Georgian Tax Law", "Audit"]
    },
    {
      id: "17",
      empNo: "HLD07",
      name: "Rəşad Quliyev Elxan Oglu",
      firstName: "Rəşad",
      lastName: "Quliyev",
      email: "reshad.guliyev@almetholding.com",
      phone: "+994 50 012 34 56",
      dateOfBirth: "1982-12-25",
      address: "Baku, Sabail district, Nizami str. 40",
      emergencyContact: "Elxan Quliyev: Father: +994 50 098 76 54",
      businessFunction: "Holding",
      department: "PROJECTS MANAGEMENT",
      unit: "STRATEGY EXECUTION",
      jobFunction: "PROJECTS MANAGEMENT",
      jobTitle: "Layihələr üzrə menecer",
      positionGroup: "MANAGER",
      grade: "5",
      lineManager: "Şirin Camalli Rasad Oglu",
      lineManagerHcNumber: "HLD01",
      startDate: "2019-03-01",
      endDate: null,
      status: "ACTIVE",
      tags: [],
      office: "Baku HQ",
      notes: "Project manager with extensive experience in strategic project execution.",
      profileImage: null,
      expertise: ["Project Management", "Strategic Planning", "Team Leadership", "Risk Management"]
    }
  ];
};

/**
 * Biznes funksiyaları siyahısını qaytarır
 * @returns {Array} - Biznes funksiyaları
 */
export const getBusinessFunctions = () => {
  return ["Holding", "Trading", "Georgia", "UK"];
};

/**
 * Departamentlər siyahısını qaytarır
 * @returns {Array} - Departamentlər
 */
export const getDepartments = () => {
  return [
    "ADMINISTRATIVE",
    "COMPLIANCE",
    "FINANCE",
    "HR",
    "OPERATIONS",
    "PROJECTS MANAGEMENT",
    "TRADE",
    "STOCK SALES",
    "BUSINESS DEVELOPMENT"
  ];
};

/**
 * Ofislər siyahısını qaytarır
 * @returns {Array} - Ofislər
 */
export const getOffices = () => {
  return ["Baku HQ", "Dubai Office", "Tbilisi Office", "London Office", "Warehouse - Surakhani"];
};

/**
 * Status siyahısını qaytarır
 * @returns {Array} - Statuslar
 */
export const getStatuses = () => {
  return ["ACTIVE", "ON LEAVE", "PROBATION", "ON BOARDING"];
};

/**
 * Vəzifə qrupları siyahısını qaytarır
 * @returns {Array} - Vəzifə qrupları
 */
export const getPositionGroups = () => {
  return [
    "BLUE COLLAR",
    "JUNIOR SPECIALIST",
    "SPECIALIST",
    "SENIOR SPECIALIST",
    "MANAGER",
    "HEAD OF DEPARTMENT",
    "DIRECTOR",
    "VC"
  ];
};